<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "30dp"

    MDIconButton:
        icon: "cog"
        pos_hint: {"right":1, "top": 1}
        icon_size: "50dp"

    MDLabel:
        text: "SHOOTER"
        haling: "center"
        font_size: "60sp"


    Image
        sourse: "assets/images/images.jfif"
        size_hint_y: 0.7
        allow_strech: True
